import { z } from "zod";
declare const configSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    APP_URL: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    GITHUB_WEBHOOK_SECRET: z.ZodString;
    GITHUB_APP_ID: z.ZodOptional<z.ZodString>;
    GITHUB_APP_PRIVATE_KEY: z.ZodOptional<z.ZodString>;
    GITHUB_APP_CLIENT_ID: z.ZodOptional<z.ZodString>;
    GITHUB_APP_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    GITHUB_TOKEN: z.ZodOptional<z.ZodString>;
    COMPASS_API_KEY: z.ZodString;
    COMPASS_API_BASE_URL: z.ZodDefault<z.ZodString>;
    COMPASS_MODEL: z.ZodDefault<z.ZodString>;
    ARTIFACTS_ROOT: z.ZodDefault<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["debug", "info", "warn", "error"]>>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    APP_URL: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    GITHUB_WEBHOOK_SECRET: string;
    COMPASS_API_KEY: string;
    COMPASS_API_BASE_URL: string;
    COMPASS_MODEL: string;
    ARTIFACTS_ROOT: string;
    LOG_LEVEL: "debug" | "info" | "warn" | "error";
    GITHUB_APP_ID?: string | undefined;
    GITHUB_APP_PRIVATE_KEY?: string | undefined;
    GITHUB_APP_CLIENT_ID?: string | undefined;
    GITHUB_APP_CLIENT_SECRET?: string | undefined;
    GITHUB_TOKEN?: string | undefined;
}, {
    DATABASE_URL: string;
    GITHUB_WEBHOOK_SECRET: string;
    COMPASS_API_KEY: string;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    APP_URL?: string | undefined;
    REDIS_URL?: string | undefined;
    GITHUB_APP_ID?: string | undefined;
    GITHUB_APP_PRIVATE_KEY?: string | undefined;
    GITHUB_APP_CLIENT_ID?: string | undefined;
    GITHUB_APP_CLIENT_SECRET?: string | undefined;
    GITHUB_TOKEN?: string | undefined;
    COMPASS_API_BASE_URL?: string | undefined;
    COMPASS_MODEL?: string | undefined;
    ARTIFACTS_ROOT?: string | undefined;
    LOG_LEVEL?: "debug" | "info" | "warn" | "error" | undefined;
}>;
export type AppConfig = z.infer<typeof configSchema>;
export declare function getConfig(env?: NodeJS.ProcessEnv): AppConfig;
export {};
